### ISSUE TITLE
JQ not installing before setting failure condition

### ISSUE THREAD

**Issue by robbymarston** [CircleCI-Public/jira-connect-orb#13]
### Orb version

Orb version: 1.0.5
Passing job: https://bit.ly/2YN8DAl
Failing job: https://bit.ly/2Kvt7sl

### What happened

I have `jira-notify` specified as the sole `post-step` for a job in my CircleCI config. When that job passes, the steps 'Install jq', 'JIRA - Setting Success Condition', and 'Update status in Atlassian Jira' run and everything works as expected. That said, when the job fails, the 'Install jq' step seems to be bypassed and the 'Update status in Atlassian Jira' step throws this error:

```
environment: line 25: jq: command not found
Exited with code 127
```

### Expected behavior

Both passing and failing jobs trigger the appropriate sequential steps, beginning with 'Install jq' and the 'Update status in Atlassian Jira' step completes without error.

**Comment by stromsvag** [comment]
I am experiencing the same issue. We are running orb version 1.0.6.

**Comment by KyleTryon** [comment]
Hello @stromsvag @robbymarston,
Sorry for the delay. I am taking a look at your issue and at a glance, it appears that this should no longer be an issue (currently 1.1.1) as the install jq step runs prior to setting the failure condition. Would either of you be able to confirm if there is still an issue? 

We will close this issue within 2 weeks if we do not hear a response.
