### ISSUE TITLE
Missing issue should not fail builds

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/jira-connect-orb#15]
### Orb version
1.0.5

### What happened

Users complaining that missing issue in commit/branch will fail the job.
https://marketplace.atlassian.com/apps/1215946/circleci-for-jira?hosting=cloud&tab=reviews

### Expected behavior

Although users might want a highly disciplined workflow (why work on things without wok items) it is clear many dont.

I suggested we default to a soft pass, and allow parameter to override.

**Comment by kevnm67** [comment]
@eddiewebb this seemed to be fixed for a while but, after updating to v1.1.6, a missing issue fails the build.

**Comment by dsayling** [comment]
@kevnm67 we believe this is currently fixed in the latest. If you're having any issues still please let us know.

**Comment by kevnm67** [comment]
@dsayling Ill report back if it happens again.  Lately everything has been working for our org.
