### ISSUE TITLE
Status does not include all deployed commits

### ISSUE THREAD

**Issue by ryanaip** [CircleCI-Public/jira-connect-orb#19]
### Orb version

1.0.6

### What happened

While deploying our new circle.yml configuration, the following sequence of builds happened:

1. Build for the pull request with our new Jira-notifying circle.yml, which failed due to some minor production-only differences in the deployment scripts.
2. Builds for a few subsequent commits that attempted to fix the failing build also failed.
3. A last commit was pushed and a build successfully ran.

### Expected behavior

The tagged Jira issue IDs for all of the commits that deployed are sent to Jira via the Orb (e.g., all stories from steps (1), (2) and (3).  (3) because it was the immediately deployed commit, and (1) and (2) because they were never successfully built, and this is the first deployment including those commits.

In the `all_commit_details` field of the build JSON, which the Orb inspects for issue keys, only the commits for the current build are provided.  However, if there are previous failed builds, I would ideally expect to see the commits from the current build as well as all previously failed builds—back in time until the most recent green build on the same branch.

I don't know the CircleCI API well, so I can think of two possible issues:

1. The Orb needs to follow the chain of failed builds backwards to collect commits from the most recent passing build, or 
2. The CircleCI API is _supposed_ to present all of the commits present (since the last passing build) in `all_commit_details`, but this doesn't work when using the v1.1 API and workflows, because one job in the workflow might pass and another fail. (It's certainly the case that `previous_successful_build` points to a previous job in the workflow, even though the overall workflow failed.)

Is it the intended behavior that when a deploy notification is triggered, it should include information from all commits (since the previous passing build)?

**Comment by eddiewebb** [comment]
This is interesting. Currently the orb only considers/matches what is known by the commit subjects passed to us by github.    While it is true `previous_successful_build` does not make much sense in workflows, my impression of `all_commit_details` was different.

Do you have any public projects that show this behavior?

**Comment by felicianotech** [comment]
Hey @ryanaip,

I'm trying to track down Issues that fell through the cracks. Is this still a problem/question?

**Comment by KyleTryon** [comment]
Closed due to inactivity

**Comment by mikesive** [comment]
Hi, I am seeing this issue as well @felicianotech. Would you recommend that I lodge a new issue?
