### ISSUE TITLE
jq: error (at <stdin>:2): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by jupe** [CircleCI-Public/jira-connect-orb#20]
### Orb version
circleci/jira@1.0.6

### What happened

JIRA orbs fails unexpectedly:

```
Attempt to get Jira Issues from https://circleci.com/api/v1.1/project/github/<team>/<project>/44
jq: error (at <stdin>:2): Cannot iterate over null (null)
Exited with code 5
```

This issue seems to be about the same: https://discuss.circleci.com/t/jira-integration-failing-at-notify-command/31698

### Expected behavior

Success run

**Comment by levlaz** [comment]
@eddiewebb we are getting more reports of this issue, it appears that this makes the orb not work at all. Can you or someone else take a look?

**Comment by eddiewebb** [comment]
@jupe - can you confirm that you are using a [USER api token](https://circleci.com/account/api) or a PROJECT token with ALL access?
![Screen Shot 2019-12-02 at 4 52 50 PM](https://user-images.githubusercontent.com/5262154/69998396-3aef7900-1524-11ea-866b-e10a43f0ea38.png)

**Comment by jupe** [comment]
I'm using Personal API Tokens.

**Comment by jupe** [comment]
I just tried circleci/jira@1.1.0 and still fails: `jq: error (at <stdin>:2): Cannot iterate over null (null)`

**Comment by eddiewebb** [comment]
We're pushing an update in #31 that includes token validation & much richer output that will isolate any issues. Sorry for those running into this issue!

**Comment by aspcanada** [comment]
This also errors out when pushing git tags...

**Comment by KyleTryon** [comment]
This issue should now be resolved. Please ensure you are using the latest version of this orb and confirm for us if you are still experiencing any issues by opening a new issue. Thank you.
