### ISSUE TITLE
Seeing 'running' build status in jira ticket

### ISSUE THREAD

**Issue by kaktusas2598** [CircleCI-Public/jira-connect-orb#26]
### What happened

Using this orb, is it possible to notify JIRA about build in running state? I only see build status once it failed or succeeded.

**Comment by eddiewebb** [comment]
Yay! I agree, coded up #32 for this. You can test it using the dev release - `circleci/jira@dev:91a6047`

please share any feedback on the way i structured the new rules in the PR description, and checkout #33 for feedback

**Comment by KyleTryon** [comment]
Closing wont do - 

Hello folks. Thank you for submitting this and letting us know you are still interested in this feature.

We will soon be working on a completely new Jira integration based on Atlassian's new "Forge" framework. We will take this feedback and include this feature into the new integration. 

We are now putting this orb integration into "maintenance" mode. We will be fixing bugs in this orb for the time being but will take all-new features to the next integration.

For this feature, we may be able to introduce this if a new webhook event is added for job starting. Currently webhooks fire at the end of a job or workflow.

Thank you.
