### ISSUE TITLE
Seeing test results in JIRA

### ISSUE THREAD

**Issue by kaktusas2598** [CircleCI-Public/jira-connect-orb#27]
### Orb version 1.1.2

Is it possible to report test results from JUnit XML format using this Orb? I used test metadata feature to see test results on build page, but I noticed in JIRA, there is a column called "test results", but it does not display anything.

Attaching image of my build status on JIRA:
![Screenshot from 2020-02-10 09-11-08](https://user-images.githubusercontent.com/4400363/74136088-673f0a00-4be5-11ea-903f-4a8c0e817cee.png)

Note "test results" are empty, but I can see test metadata on CircleCI build page.

**Comment by eddiewebb** [comment]
Love this! It would of course be possible to re-parse any of the test-output, but let me see if our build agent does any of the test processing container side, or someway to avoid duplicate work.

**Comment by andormarkus** [comment]
Hi @eddiewebb 
Do you have any update in this enhancement?
Thanks, Andor

**Comment by mrea1** [comment]
+1 would love this

**Comment by KyleTryon** [comment]
Hello folks. Thank you for submitting this and letting us know you are still interested in this feature.

We will soon be working on a completely new Jira integration based on Atlassian's new "Forge" framework. We will take this feedback and include this feature into the new integration. 

We are now putting this orb integration into "maintenance" mode. We will be fixing bugs in this orb for the time being but will take all-new features to the next integration.

Thank you.

**Comment by benedekAKoncz** [comment]
Hi @KyleTryon do you have any update on the new "Forge-based" implementation? When will that be available?
