### ISSUE TITLE
the build number is always 1

### ISSUE THREAD

**Issue by michael-demian** [CircleCI-Public/jira-connect-orb#29]
### Orb version
circleci/jira@1.1.2

### What happened

the build number is always 1 and always has just one build record (just with updated last update time)  in Jira

I think the build number depends on ${CIRCLE_BUILD_NUM}, so tried to check it and it is working fine and has value 193

`Attempt to get Jira Issues from  https://circleci.com/api/v1.1/project/github/talabat-dhme/POSMiddleware/193
Job is passing, workflow is null
Results from Jira: 
Success!
{
  "acceptedBuilds": [
    {
      "pipelineId": "POSMiddleware",
      "buildNumber": 1
    }
  ],
  "rejectedBuilds": [],
  "unknownIssueKeys": [
    "OPSC-812"
  ]
}`
### Expected behavior

every Build should have a new number and add a new build record on JIRA

**Comment by eddiewebb** [comment]
This will be fixed by #31 and can be tested with `circleci//jira@dev:ccd6b20`

**Comment by eddiewebb** [comment]
( please confirm if you can and let me know if anything is not working, apologies for the trouble!)

**Comment by gmemstr** [comment]
I'm going to assume this is fixed in #31, @michael-demian I'm going to go ahead and close this issue but feel free to reopen if you find this isn't the case.
