### ISSUE TITLE
Cannot see successful build statuses in JIRA

### ISSUE THREAD

**Issue by kaktusas2598** [CircleCI-Public/jira-connect-orb#30]
### Orb version

1.1.2

### What happened

We were able to see successful and failing builds on JIRA ticket last week, but this week for some reason we can only see failed builds. Nothing has changed in CircleCI config

Inside CircleCI "Update status in Atlassian JIRA" step, I can see one difference for successful build, which might indicate why it is not posting status to ticket:

```
Job is passing, workflow is null
Results from Jira: 
Success!
{
  "acceptedBuilds": [
    {
      "pipelineId": "pi-app",
      "buildNumber": 1
    }
  ],
  "rejectedBuilds": [],
  "unknownIssueKeys": []
}
```

Notice, that message "Job is passing, workflow is null" is only visible on successful builds, hence this might indicate that issue is.

### Expected behavior

I expect to see successful builds as well on JIRA ticket.

**Comment by eddiewebb** [comment]
Sorry to hear about the trouble.  There is in flight change that likely corrected this. Would you be willing to confirm with a `dev` release of the orb?
`circleci/jira@dev:ccd6b20` witll expire in ~90 days, but is the current release candiate from #31

**Comment by kaktusas2598** [comment]
I have tried using  ```circleci/jira@dev:ccd6b20``` and got this error while trying to send status to JIRA in my Circle job:

```401:https://circleci.com/api/v2/me
Curl failed with code 401. full response below.
{
  "message" : "You must log in first."
}
```

**Comment by JoshStaff** [comment]
> I have tried using `circleci/jira@dev:ccd6b20` and got this error while trying to send status to JIRA in my Circle job:
> 
> ```
> Curl failed with code 401. full response below.
> {
>   "message" : "You must log in first."
> }
> ```

Same error for me. Any idea on how to move forwards @eddiewebb? Thanks in advance!

**Comment by vladgolubev** [comment]
Version `1.1.4` is broken, reverting to `1.1.3` helps

**Comment by gmemstr** [comment]
Hi all - is anyone able to verify whether this issue persists in the latest release (1.2.0)?

**Comment by gmemstr** [comment]
Going ahead and closing this since it's related to an older version. If you are still encountering this issue, feel free to reopen with more details!
