### ISSUE TITLE
Show pending deploys

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/jira-connect-orb#33]
### Orb version

When #32 is (was) merged, it added pending status when an approval is blocking the workflow.

this should be optimized to consider deployments specially. 
 - it should be possible to look forward and see if there is a gated deployment to send as "pending".

- in scenarios that this job is followed by approval (covered in #32)
- IF downstream job is setting deployment parameter (need to introspect config)
 - THEN send final status for build side, and mark deployment as pending.

**Comment by KyleTryon** [comment]
Hello folks. Thank you for submitting this and letting us know you are still interested in this feature.

We will soon be working on a completely new Jira integration based on Atlassian's new "Forge" framework. We will take this feedback and include this feature into the new integration. 

We are now putting this orb integration into "maintenance" mode. We will be fixing bugs in this orb for the time being but will take all-new features to the next integration.

Thank you.
