### ISSUE TITLE
Please start tagging releases

### ISSUE THREAD

**Issue by philCryoport** [CircleCI-Public/jira-connect-orb#34]
### Orb version

1.1.2

### What happened

I just found out we're using an older orb than 1.1.2 and went to look at the code changes that have happened since then.  Only version 0.0.1 is tagged as a release. 

I'm able to find the source code for v1.1.2 in the orb registry -- https://circleci.com/orbs/registry/orb/circleci/jira?version=1.1.2 -- so I can manually diff the code changes, but it would be nice if I could leverage Github's code diff capabilities to compare versions.

 I couldn't find a changelog either.

### Expected behavior

Orb dev team tags releases in the Github repo -- and perhaps also includes a changelog as well

**Comment by lokst** [comment]
Thank you for your feedback. We've started doing this in some of other orbs and plan to implement it in this orb too.

**Comment by KyleTryon** [comment]
@philCryoport Thank you for the feedback and usecase. We will implement this today. I will report back when this is complete 👍

**Comment by KyleTryon** [comment]
Published updates are now tagged as releases: https://github.com/CircleCI-Public/jira-connect-orb/releases

Thank you for sharing your feedback 👍
