### ISSUE TITLE
jq: error (at <stdin>:549): null (null) cannot be matched, as it is not a string

### ISSUE THREAD

**Issue by aspcanada** [CircleCI-Public/jira-connect-orb#35]
### Orb version

1.1.2

### What happened

When building a git tag in Circle, there is no branch. In the /tmp/job_info.json, the branch key is null.
- `"branch": null,` 

### Expected behavior

orb should fail gracefully upon not finding any ISSUE_KEYS

**Comment by aspcanada** [comment]
might be able to add `| select (.branch!=null)` after the .branch in the final jq query...

**Comment by aspcanada** [comment]
I have a fix for this...

Simply replace `.branch` > `if .branch then .branch else "" end ` on line 73 of notify.yml

src/commands/notify.yml:73
`          ISSUE_KEYS=$(cat /tmp/job_info.json | jq '[.all_commit_details[].subject | scan("(<<parameters.issue_regexp>>)")   | .[] ] + [.all_commit_details[].branch | scan("(<<parameters.issue_regexp>>)")   | .[] ] + [if .branch then .branch else "" end | scan("(<<parameters.issue_regexp>>)")  | .[] ]')
`

**Comment by aspcanada** [comment]
@eddiewebb, I can open a PR is you'd like...

**Comment by lokst** [comment]
@aspcanada It would be wonderful if you could open a PR for this, thank you! (@KyleTryon @eddiewebb )

**Comment by KyleTryon** [comment]
Hey all, taking a look today. @aspcanada thank you for the assistance. We will update this by end of day and report back here.

**Comment by randywallace** [comment]
I ran into this today as well; one thing I observed in troubleshooting this, is that, as this is a tag, there is no commit/branch/pr information to derive an Issue ID from (from the API response); as such, if the vcs_tag is populated in the job json response, why not just skip pinging Jira at all and exit early with something that exits 0 and mentions as much
