### ISSUE TITLE
circleci/jira to run jq/install if default shell is /bin/sh

### ISSUE THREAD

**Issue by damiendube** [CircleCI-Public/jira-connect-orb#37]
### Orb version
1.1.2

### What happened
Running on image docker:18.06.3-ce-git, which is based of alpine 3.9.
jira/notify fails to install jq.
Error message is 
```
sh: 0: unknown operand
/bin/sh: syntax error: unexpected "(" (expecting "fi")
```
This is due to jq/install using the /bin/sh shell instead of /bin/bash.
I've installed bash prior to running this task and it didn't fix the issue.

### Expected behavior
jq/install states on their doc that they required bash but is not using it. Not sure id that is a circleci/jira issue or a circleci/jq issue. Please advise

**Comment by lokst** [comment]
Hi @damiendube , closing this issue here as we can continue the discussion in https://github.com/CircleCI-Public/jq-orb/issues/14 🙂
