### ISSUE TITLE
Add ability to post deployment link

### ISSUE THREAD

**Issue by michalochman** [CircleCI-Public/jira-connect-orb#4]
Hi! Both `build` and `deployment` notifications work great, however I think it would be event better if it was possible to somehow let the orb know what is the URL to deployment. I'm gonna use your issue template for this feature request even thought it's more suited for bug reports 😉

### Orb version

1.0.2

### What happened

`job_type: deployment` links to CircleCI job, which makes more sense for `build` type:
<img src="https://user-images.githubusercontent.com/1628450/57036404-7f482d00-6c54-11e9-8939-a5715c0f737c.png" width="402" />

### Expected behavior

It would be great if `job_type: deplyoment` additionally linked to actual release (quick mockup):
<img src="https://user-images.githubusercontent.com/1628450/57036716-58d6c180-6c55-11e9-95ed-b7444bbc7f88.png" width="402" />

I am not sure what is the best way to approach this, but it could be parameter that we use with the orb, like the `environment_type` or maybe there's an easier way like setting an environment variable.

**Comment by eddiewebb** [comment]
Hi @michalochman, thanks for sharing the suggestion!  The orb's interaction is limited by the API exposed in Jira - https://developer.atlassian.com/cloud/jira/software/rest/#api-rest-deployments-0-1-bulk-post, and we don't have influence on rendering of the data.

To my interpretation it really only leaves us the Description and Display Name to provide this, but neither would be linkable.

I think it's worth sharing the feedback with Jira's Product team though, you can add a new suggestion here, https://jira.atlassian.com/secure/CreateIssue!default.jspa (I didn't find any matches existing)

**Comment by michalochman** [comment]
Hi @eddiewebb, by "actual release" I meant both "actual running app" and "artifact repo" – in generic scenario the deployment doesn't have to be an app, it may be an artifact as well.

In the example looks like the API suggests `deployments[X].url` field for that:
> `"url": "http://mydeployer.com/project1/1111-222-333/prod-east",`

Is it what you use to link the "#42 awesome_repo - deploy" text from my first screenshot back to CircleCI job?

I think that your idea to make the URL overridable might work, the default can be what you use now.

**Comment by eddiewebb** [comment]
Exactly. The payload has 2 URLs, one represents the "pipeline" which is the whole project in CircleCI terminology, and the 2nd URL represents the deployment itself, which is documented to be the specific job, but I'm not sure why that couldn't be left to the preference of each user.

**Comment by KyleTryon** [comment]
Hello Friends 👋 

The day has finally come 🎉 ! As we have alluded to in a few spots in this repository, we have been working on a new integration for Jira with CircleCI to replace this outdated orb which has historically been difficult for us to update. Today we are excited to announce Jira Integration V2 is finally LIVE!

**New Docs:** https://circleci.com/docs/jira-plugin/
**Orb v2:** 
* Registry: https://circleci.com/developer/orbs/orb/circleci/jira
* Source: https://github.com/CircleCI-Public/jira-orb

**Atlassian Forge App:** https://github.com/CircleCI-Public/circleci-for-jira

## Key Features
 - Open-ID Connect Authentication - No Personal Access Tokens or API keys!
 - Fully open source orb with Atlassian Forge backend.
 - Optimized orb experience, now much easier to configure.

## What to know
 - This repo (https://github.com/CircleCI-Public/jira-connect-orb) will be _**archived**_ shortly.
 - We have attempted to address all current issues with this next generation integration. If you experience any issues or have any feature requests please open a new issue in the new repository.
 - A video demonstration will be coming out soon.
 - We highly recommend moving to v2 of the orb as soon as possible.
