### ISSUE TITLE
200 Response is being marked as a failure

### ISSUE THREAD

**Issue by Vivalldi** [CircleCI-Public/jira-connect-orb#49]
### Orb version

`circleci/jira@1.2.2`

### What happened

Was using the `jira/notify` command to mark a deployment for a service. The `verify_api_key` step fails due to the fetch function. A valid response of 200 is marked as a failure.

Here is the output of the `Update status in Atlassian Jira` step
```
200:https://circleci.com/api/v2/me?circle-token=****************************************
Curl failed with code 200. full response below.
{
  "name" : "my name",
  "login" : "username",
  "id" : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx"
}

Exited with code exit status 1
```

Unable to link due to it being a private project.

### Expected behavior

`fetch` should not error on a `HTTP_200_OK` response.

**Comment by gmemstr** [comment]
This is very bizarre, and not something I'm sure how to replicate. Digging a bit deeper.

**Comment by Vivalldi** [comment]
It's been a while, but if needed I can probably dig in to find the job. I can also probably run again as I find time

**Comment by gmemstr** [comment]
@Vivalldi That would be extremely helpful. Can you also confirm what image you're using in the job encountering this issue?

**Comment by Vivalldi** [comment]
Source: bitbucket
Org: mondobrain
Project: helotia
Job: 16
Image: `hashicorp/terraform:0.12.26`

**Comment by gmemstr** [comment]
After some digging, it looks like this issue was solved in version 1.1.7, which is a patch version directly after the version that was used in the particular build. We have made a lot of improvements since then, so I'd recommend giving the latest version (`1.3.1`) a try :)

**Comment by Vivalldi** [comment]
Thanks for the update! It has been a while since I've attempted to use this orb. Happy to close this issue if it appears resolved on your end (I probably won't get around to using it for a while)

**Comment by andormarkus** [comment]
Hi @Vivalldi @gmemstr 

I was able isolate track down the issue and caused by alpine based images (terraform is alpine based). 
The orb does not work with alpine based images and issue is raised in #64
