### ISSUE TITLE
Other way of extracting issue keys from the payload data?

### ISSUE THREAD

**Issue by lubieniebieski** [CircleCI-Public/jira-connect-orb#5]
### Orb version

1.0.2

### What happened

1. I have the issue key saved in branch name `ABC-123-test`
    1. I don't really find it useful to repeat issue key name in my commit, but ok, I try:
1. I have a commit message with multiple lines, when issue key `ABC-123`is saved in the last line, so it looks like this:
    ```a commit message
    with multiple lines
    and issue key
    being in the last one (for clarity)
    ABC-123
    ```
1. The `subject` key in `all_commit_details` contains only the first line, so there's no way to extract the issue key
1. As the result I get the message at the end of CircleCI build: 
`{"acceptedBuilds":[],"rejectedBuilds":[{"key":{"pipelineId":"XXX","buildNumber":1},"errors":[{"message":"At least one 'issueKeys' is required"}]}],"unknownIssueKeys":[]}Success!`

### Expected behavior

I would like the script to extract the data from `branch` key within `all_commit_details` first and then try `subject` (which should contain the entire commit message body).

Please let me know if there's anything to clarify!

**Comment by eddiewebb** [comment]
I'm not sure accessing the entire payload is viable currently as we need to scan all possible commits for a single build and that can be nuanced from just `git` commands in different checkout scenarios. This is why we rely on the payload provided by github that summarizes all commits in the push, but is limited to subject only.

Capturing from branch is certainly viable though and an interesting pattern to explore.

**Comment by iynere** [comment]
`v1.0.4` of the orb will include the fix for this
