### ISSUE TITLE
Feature: Add ability to change JIRA ticket status

### ISSUE THREAD

**Issue by mvxt** [CircleCI-Public/jira-connect-orb#50]
### Expected behavior

Would be nice to have a command that can change an issue's status. Use is automation, for example when tests pass for a particular ticket/branch, ticket moves to Done, etc.

Example: https://community.atlassian.com/t5/Jira-Questions/JIRA-How-to-change-issue-status-via-rest/qaq-p/528133

**Comment by bpatram** [comment]
Have you tried setting up an Automation rule in Jira to do this? 


For deployments you can use a [Deployment Success/Failed/Changed triggers](https://support.atlassian.com/jira-software-cloud/docs/automation-triggers/#Automationtriggers-Deploymentfailed) and for builds you can use the [Build Success/Failed/Changed triggers](https://support.atlassian.com/jira-software-cloud/docs/automation-triggers/#Automationtriggers-Buildfailed) and then use a [Transition Issue action](https://support.atlassian.com/jira-software-cloud/docs/automation-actions/#Automationactions-Transitionissue).

Like this:
![image](https://user-images.githubusercontent.com/5579960/127595358-baddfb60-fb28-4acf-bef6-9d2caf2b65e9.png) ![image](https://user-images.githubusercontent.com/5579960/127594696-8fd632d6-389b-4dd4-a9d3-63b4676a8bda.png)

**Comment by KyleTryon** [comment]
Marking closed - inactive. It appears @bpatram has supplied a viable solution for the current integration.
