### ISSUE TITLE
Feature: Add support for GitHub Enterprise

### ISSUE THREAD

**Issue by chetanyakan** [CircleCI-Public/jira-connect-orb#52]
### Expected behavior

The code to check the VCS type currently checks for the presence of `github.com` in the repository URL and would not work for GitHub enterprise.

Refer: https://github.com/CircleCI-Public/jira-connect-orb/blob/92558ce1406f22358ebf328b5dadc3ff8a6ae46f/src/commands/notify.yml#L54

**Comment by gmemstr** [comment]
@chetanyakan CircleCI cloud doesn't support GitHub Enterprise, and CircleCI server does not support orbs - going ahead and closing this issue for now, but we may need to revisit later down the line if one of those two points changes. Should be relatively easy.
