### ISSUE TITLE
Complete Atlassian Security Self-Assessment Program

### ISSUE THREAD

**Issue by mathroule** [CircleCI-Public/jira-connect-orb#54]
Hi

The CircleCI Jira integration https://marketplace.atlassian.com/apps/1215946/circleci-for-jira has not completed the Security Self-Assessment Program. See https://developer.atlassian.com/platform/marketplace/security-self-assessment-program.

Is it planned to complete the Security Self-Assessment Program for the CircleCI Jira integration?

Created from https://support.circleci.com/hc/en-us/requests/81565.

### Orb version
N/A

### What happened
N/A

### Expected behavior
N/A

**Comment by gmemstr** [comment]
Note: This is less to do with the orb and more to do with the integration within the marketplace, from what I can tell. Leaving open until we have investigated further.

**Comment by KyleTryon** [comment]
Internal reference: SEC-1744

**Comment by KyleTryon** [comment]
Completed
