### ISSUE TITLE
Allow custom deployment description

### ISSUE THREAD

**Issue by weitzman** [CircleCI-Public/jira-connect-orb#70]
Today the orb hardcodes `--arg description "${CIRCLE_PROJECT_REPONAME} #${CIRCLE_BUILD_NUM} ${CIRCLE_JOB}"`. I would love to override that with parameters that were specific to this deployment.

**Comment by KyleTryon** [comment]
Hello folks. Thank you for submitting this and letting us know you are still interested in this feature.

We will soon be working on a completely new Jira integration based on Atlassian's new "Forge" framework. We will take this feedback and include this feature into the new integration. 

We are now putting this orb integration into "maintenance" mode. We will be fixing bugs in this orb for the time being but will take all-new features to the next integration.

For this feature in particular, the next version of this orb will be based off webhooks (most likely) which would likely allow for less customization, though an easier setup experience. We will look into how much customization can be achieved on the Atlassian side of the equation

Thank you.
