### ISSUE TITLE
Orb requires a PERSONAL token and does not work with project tokens

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [CircleCI-Public/jira-connect-orb#77]
### Orb version

1.3.1

### What happened

Create a project token
Put it in CIRCLE_CI in a context
Add the orb to config.yml
Add a jira/notify step
The job fails with "You must log in first." after trying to curl https://circleci.com/api/v2/me?circle-token=${CIRCLE_TOKEN}

### Expected behavior

The orb should work with project tokens. 

It is insane to require *personal* tokens for an automated CI/CD job. What happens when I rotate my personal key? What happens when I leave the company? Do all our builds fail now?

**Comment by matiaslauriti** [comment]
I totally agree with you, and at the beginning I truly did not understand that I must use a _personal token_...

But I think this repo/orb is totally dead... nothing else happened and they still have to implement the new API into the Orb... and we are still waiting... if you want to show deployments on Jira and you have more than 1 ticket on that PR, it will not work or just use 1 ticket number... totally crazy...

**Comment by donholly** [comment]
+1

**Comment by nicowenterodt** [comment]
Any news on that? We also have problems using personal token leading to 401 "You must log in first" errors.
