### ISSUE TITLE
{{build.name}} returns repository name, not destination branch

### ISSUE THREAD

**Issue by MoochaelCorcoran** [CircleCI-Public/jira-connect-orb#82]
### Orb version
 1.3.1

### What happened
Creating Jira automations and build.name is returning the repository name and not the destination branch
![image](https://user-images.githubusercontent.com/100386526/155619810-7c4ec69c-263b-4df9-b016-6055a8ca7283.png)
Note here the repo name is testing.

Got the expected output by changing line 164 in `generate_json_payload_build` from `CIRCLE_PROJECT_REPONAME` to `CIRCLE_BRANCH`.

![image](https://user-images.githubusercontent.com/100386526/155620445-e5a19fcf-83c6-42d6-bf50-3853610025f4.png)

### Expected behavior

{{build.name}} references the destination branch name and not the repository name.

**Comment by KyleTryon** [comment]
Hello Friends 👋 

The day has finally come 🎉 ! As we have alluded to in a few spots in this repository, we have been working on a new integration for Jira with CircleCI to replace this outdated orb which has historically been difficult for us to update. Today we are excited to announce Jira Integration V2 is finally LIVE!

**New Docs:** https://circleci.com/docs/jira-plugin/
**Orb v2:** 
* Registry: https://circleci.com/developer/orbs/orb/circleci/jira
* Source: https://github.com/CircleCI-Public/jira-orb

**Atlassian Forge App:** https://github.com/CircleCI-Public/circleci-for-jira

## Key Features
 - Open-ID Connect Authentication - No Personal Access Tokens or API keys!
 - Fully open source orb with Atlassian Forge backend.
 - Optimized orb experience, now much easier to configure.

## What to know
 - This repo (https://github.com/CircleCI-Public/jira-connect-orb) will be _**archived**_ shortly.
 - We have attempted to address all current issues with this next generation integration. If you experience any issues or have any feature requests please open a new issue in the new repository.
 - A video demonstration will be coming out soon.
 - We highly recommend moving to v2 of the orb as soon as possible.
