### ISSUE TITLE
Handling HTTP errors gracefully

### ISSUE THREAD

**Issue by hamvocke** [CircleCI-Public/jira-connect-orb#86]
### Orb version

1.3.1

### What happened

We're running `jira/notify` as a regular step in some of our jobs:

```yml
  - jira/notify:
      token_name: CIRCLECI_TOKEN
```

When trying to notify Jira (cloud hosted) from CircleCI via the Jira connect orb, the notification step sometimes fails when Jira returns a `HTTP 503` status code. This causes the entire `jira/notify` step to fail which in turn makes the entire CircleCI job fail.

### Expected behavior

Not being able to notify Jira is not the end of the world. It would be great if we could handle HTTP failures more gracefully - especially in a case like a `503` response, where there's really nothing we can do on our end to save the day.

It seems like the orb is already trying to fail gracefully in the `post_to_jira` step:

https://github.com/CircleCI-Public/jira-connect-orb/blob/ff2f464cb81bb4aeac56dae2d03338bad97133d6/src/commands/notify.yml#L245-L248

However, there are multiple `fetch` calls using `curl` internally, and if those fail (e.g. with a `503` as I mentioned above) the entire step fails with an `exit 1`:

https://github.com/CircleCI-Public/jira-connect-orb/blob/ff2f464cb81bb4aeac56dae2d03338bad97133d6/src/commands/notify.yml#L94-L97

I could see a few solutions to this problem:

1. fail gracefully (e.g. with `exit 0`) if there's a `5xx` response - there's nothing I could do if the server responds with a server-side error
2. retry the `curl` calls if there's a `503` response - usually these are blips that might recover when retrying a few seconds later. `curl`'s got pretty [convenient retry mechanisms baked in](https://stackoverflow.com/questions/42873285/curl-retry-mechanism).
3. allow explicitly declaring that I don't care about errors in the `jira/notify` step and want to move on regardless of failed HTTP requests

**Comment by JustinAiken** [comment]
A vote for number 1 or 3; today we're seeing a 100% fail rate because of cloudfront errors; retry wouldn't help.

**Comment by bartimez** [comment]
Would also vote for 1 or 3.  We are seeing the same issue when Jira returns a `504`, causing builds to fail completely:

```
Results from Jira: 
Error calling Jira, result: 504
parse error: Invalid numeric literal at line 1, column 10

Exited with code exit status 4
```

**Comment by RangerRick** [comment]
Yes, please. There is nothing more frustrating than to have a job "fail" [just because it failed to post its "success" status to JIRA](https://app.circleci.com/pipelines/github/OpenNMS/opennms/30359/workflows/0716c403-9455-481a-af18-f96088443317/jobs/262725/parallel-runs/9?filterBy=FAILED) temporarily. _especially_ when it's CircleCI having the issue communicating with their own services:

```
Curl failed with code 500. full response below.
{
  "message" : "Failed to fetch workflow"
}
```

I'd love to see retries, or at least an option to treat failures as non-fatal.

**Comment by KyleTryon** [comment]
Hello Friends 👋 

The day has finally come 🎉 ! As we have alluded to in a few spots in this repository, we have been working on a new integration for Jira with CircleCI to replace this outdated orb which has historically been difficult for us to update. Today we are excited to announce Jira Integration V2 is finally LIVE!

**New Docs:** https://circleci.com/docs/jira-plugin/
**Orb v2:** https://circleci.com/developer/orbs/orb/circleci/jira
**Atlassian Forge App:** https://github.com/CircleCI-Public/circleci-for-jira

## Key Features
 - Open-ID Connect Authentication - No Personal Access Tokens or API keys!
 - Fully open source orb with Atlassian Forge backend.
 - Optimized orb experience, now much easier to configure.

## What to know
 - This repo (https://github.com/CircleCI-Public/jira-connect-orb) will be _**archived**_ shortly.
 - We have attempted to address all current issues with this next generation integration. If you experience any issues or have any feature requests please open a new issue in the new repository.
 - A video demonstration will be coming out soon.
 - We highly recommend moving to v2 of the orb as soon as possible.
