### ISSUE TITLE
✨ Feature: add ability to pass environment_type via environment variable

### ISSUE THREAD

**Issue by a-tokyo** [CircleCI-Public/jira-connect-orb#87]
### Orb version 1.x

Can we add the ability to pass environment_type via env variables? This way we can have one workflow for all environments instead of creating a hardcoded workflow per env.

Thanks!

**Comment by KyleTryon** [comment]
Hello Friends 👋 

The day has finally come 🎉 ! As we have alluded to in a few spots in this repository, we have been working on a new integration for Jira with CircleCI to replace this outdated orb which has historically been difficult for us to update. Today we are excited to announce Jira Integration V2 is finally LIVE!

**New Docs:** https://circleci.com/docs/jira-plugin/
**Orb v2:** https://circleci.com/developer/orbs/orb/circleci/jira
**Atlassian Forge App:** https://github.com/CircleCI-Public/circleci-for-jira

## Key Features
 - Open-ID Connect Authentication - No Personal Access Tokens or API keys!
 - Fully open source orb with Atlassian Forge backend.
 - Optimized orb experience, now much easier to configure.

## What to know
 - This repo (https://github.com/CircleCI-Public/jira-connect-orb) will be _**archived**_ shortly.
 - We have attempted to address all current issues with this next generation integration. If you experience any issues or have any feature requests please open a new issue in the new repository.
 - A video demonstration will be coming out soon.
 - We highly recommend moving to v2 of the orb as soon as possible.
