### ISSUE TITLE
Deployments to the same environment are treated as different environments

### ISSUE THREAD

**Issue by ryanpf** [CircleCI-Public/jira-connect-orb#88]
### Orb version

1.3.1

### What happened

1. A deployment failed, Jira was notified
2. A future deployment succeeded, Jira was notified
3. The deployment list for the issue on Jira shows overall failure

![image](https://user-images.githubusercontent.com/2955908/205163206-e9f4a08a-ac6a-48fc-8497-eba3031fa99b.png)
![image](https://user-images.githubusercontent.com/2955908/205163153-f0b2c427-24d7-4d43-a5c7-c15305c6fdf0.png)

### Expected behavior

The deployment list for the issue should show only the latest deployment. The overall deployment status should be Success.

I think this is happening because the `environment.id` supplied is using `CIRCLE_WORKFLOW_ID`, which changes for every run. I think `CIRCLE_PROJECT_REPONAME` is a good candidate to replace the usage of `CIRCLE_WORKFLOW_ID` here.
`--arg envId "${CIRCLE_WORKFLOW_ID}-<<parameters.environment>>"`
I got this from the source code at https://circleci.com/developer/orbs/orb/circleci/jira

**Comment by KyleTryon** [comment]
Hello Friends 👋 

The day has finally come 🎉 ! As we have alluded to in a few spots in this repository, we have been working on a new integration for Jira with CircleCI to replace this outdated orb which has historically been difficult for us to update. Today we are excited to announce Jira Integration V2 is finally LIVE!

**New Docs:** https://circleci.com/docs/jira-plugin/
**Orb v2:** https://circleci.com/developer/orbs/orb/circleci/jira
**Atlassian Forge App:** https://github.com/CircleCI-Public/circleci-for-jira

## Key Features
 - Open-ID Connect Authentication - No Personal Access Tokens or API keys!
 - Fully open source orb with Atlassian Forge backend.
 - Optimized orb experience, now much easier to configure.

## What to know
 - This repo (https://github.com/CircleCI-Public/jira-connect-orb) will be _**archived**_ shortly.
 - We have attempted to address all current issues with this next generation integration. If you experience any issues or have any feature requests please open a new issue in the new repository.
 - A video demonstration will be coming out soon.
 - We highly recommend moving to v2 of the orb as soon as possible.
